Repository poanetwork/poa-popa, pull requests merged in 2018-02, with the labels that each got.

#32 (Improvement) Add description of this DApp
  README.md
Labels: in progress

#30 (Refactor) Notify register transaction file
  scripts/test-api.js
  web-dapp/controllers/notifyRegTx.js
  web-dapp/routes/notify_reg_tx.js
  web-dapp/server-lib/session-stores/memory.js
  web-dapp/server-lib/utils.js
Labels: in progress, scope-server-api

#36 (Refactor) Make redis storage files to use promises
  web-dapp/server-lib/session-stores/memory.js
  web-dapp/server-lib/session-stores/redis.js
  web-dapp/server-lib/utils.js
Labels: in progress

#37 (Fix) Remove scripts/test-api.js file
  scripts/test-api.js
Labels: in progress

#39 (Test) Add basic tests for register_address method
  blockchain/contracts/ProofOfPhysicalAddress.sol
  blockchain/migrations/1517251265_popa.js
  blockchain/test/proof_of_physical_address.js
  blockchain/truffle-config.js
  blockchain/truffle.js
  package-lock.json
  package.json
Labels: in progress, scope-contract-tests

#41 (Refactor) Move signature logic to function
  blockchain/test/proof_of_physical_address.js
  web-dapp/routes/index.js
  web-dapp/routes/prepare_con_tx.js
  web-dapp/routes/prepare_reg_tx.js
  web-dapp/server-lib/buildSignature.js
  web-dapp/server-lib/sign.js
Labels: in progress, score-server-lib

#43 (Test) Add solidity-coverage
  blockchain/.gitignore
  blockchain/.solcover.js
  blockchain/package-lock.json
  blockchain/package.json
  blockchain/test/proof_of_physical_address.js
  blockchain/truffle.js
Labels: in progress

#44 (Fix) Error in relative paths
  web-dapp/server-config.js
  web-dapp/server-lib/logger.js
  web-dapp/server.js
Labels: in progress

#45 (Feature) Add tests and coverage to notifyRegTx controller
  web-dapp/.eslintrc.yml
  web-dapp/controllers/notifyRegTx.js
  web-dapp/package.json
  web-dapp/routes/notify_reg_tx.js
  web-dapp/routes/prepare_con_tx.js
  web-dapp/routes/prepare_reg_tx.js
  web-dapp/server-config.js
  web-dapp/server-lib/get_address_details.js
  web-dapp/server-lib/get_address_index.js
  web-dapp/server-lib/get_transaction.js
  web-dapp/server-lib/post_api.js
  web-dapp/server-lib/validate_address_index.js
  web-dapp/server-lib/validate_tx_details.js
  web-dapp/server-lib/validate_tx_info.js
  web-dapp/server-lib/validations.js
  web-dapp/test/server/_utils/mock-contract-output.json
  web-dapp/test/server/_utils/mocks.js
  web-dapp/test/server/index.js
  web-dapp/test/server/log_request.spec.js
  web-dapp/test/server/logger.spec.js
  web-dapp/test/server/notifyRegTx.spec.js
  web-dapp/test/server/validations.spec.js
Labels: in progress

#48 (Test) Use locally installed truffle
  blockchain/.solcover.js
  blockchain/package-lock.json
  blockchain/package.json
  package-lock.json
  package.json
Labels: in progress

#50 (Fix) Syntax errors, incorrect path
  package.json
  web-dapp/routes/notify_reg_tx.js
  web-dapp/server-lib/get_address_details.js
Labels: in progress

#53 (Bug) Address registration error
  web-dapp/controllers/notifyRegTx.js
  web-dapp/routes/notify_reg_tx.js
Labels: in progress

#54 (Fix) typo in wallet check condition
  web-dapp/routes/prepare_con_tx.js
Labels: in progress

#56 (Improvement) Add more tests to server-lib files
  web-dapp/server-lib/validate_tx_details.js
  web-dapp/test/server/_utils/mocks.js
  web-dapp/test/server/get_address_details.spec.js
  web-dapp/test/server/get_address_index.spec.js
  web-dapp/test/server/get_transaction.spec.js
  web-dapp/test/server/validate_address_index.spec.js
  web-dapp/test/server/validate_tx_details.spec.js
Labels: in progress
