Repository poanetwork/poa-popa, pull requests merged in 2018-03, with the labels that each got.

#58 (Improvement) Use winston as logger
  web-dapp/package-lock.json
  web-dapp/package.json
  web-dapp/server-lib/logger.js
Labels: in progress

#59 (Refactor) Refactor of prepare_reg_tx route
  web-dapp/controllers/prepareRegTx.js
  web-dapp/routes/prepare_reg_tx.js
  web-dapp/server-lib/post_api.js
  web-dapp/test/server/get_address_details.spec.js
  web-dapp/test/server/get_address_index.spec.js
  web-dapp/test/server/get_transaction.spec.js
  web-dapp/test/server/notifyRegTx.spec.js
  web-dapp/test/server/prepareRegTx.spec.js
  web-dapp/test/server/validate_address_index.spec.js
  web-dapp/test/server/validate_tx_details.spec.js
Labels: in progress

#62 (Fix) Issue#61
  web-dapp/routes/notify_reg_tx.js
  web-dapp/server-lib/validate_tx_info.js
  web-dapp/test/server/_utils/mocks.js
Labels: in progress

#55 (Feature) Check that contract is deployed by requesting owner
  web-dapp/src/components/App.js
Labels: in progress

#65 (Fix) condition in confirmation code generation
  web-dapp/server-lib/generate_code.js
  web-dapp/test/server/generate_code.spec.js
Labels: in progress, score-server-lib

#66 (Improvement) Add code freq test
  web-dapp/test/server/generate_code.spec.js
Labels: in progress, score-server-lib

#63 (Refactor) Refactor of prepare_con_tx route
  web-dapp/controllers/prepareConTx.js
  web-dapp/routes/prepare_con_tx.js
  web-dapp/server-lib/validations.js
  web-dapp/test/server/_utils/mocks.js
  web-dapp/test/server/prepareConTx.spec.js
  web-dapp/test/server/prepareRegTx.spec.js
Labels: in progress, scope-server-api, score-server-lib

#73 (Improvement) Add test and coverage to the web-dapp
  .gitignore
  web-dapp/.gitignore
  web-dapp/package-lock.json
  web-dapp/package.json
  web-dapp/src/assets/javascripts/init-my-web3.js
  web-dapp/src/assets/stylesheets/application.css
  web-dapp/src/assets/stylesheets/application/_4_base.scss
  web-dapp/src/components/App.js
  web-dapp/src/components/App.test.js
  web-dapp/src/components/ConfirmationPage.js
  web-dapp/src/components/ConfirmationPage.test.js
  web-dapp/src/components/Footer.js
  web-dapp/src/components/Footer.test.js
  web-dapp/src/components/Header.js
  web-dapp/src/components/Header.test.js
  web-dapp/src/components/Loading.js
  web-dapp/src/components/Loading.test.js
  web-dapp/src/components/RegisterAddressPage.js
  web-dapp/src/components/RegisterAddressPage.test.js
  web-dapp/src/contract-output.json
  web-dapp/src/setupTests.js
Labels: in progress

#76 (Improvement) Update README file
  README.md
Labels: in progress

#80 (Improvement) Add tests to API's routes
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  web-dapp/app.js
  web-dapp/controllers/prepareRegTx.js
  web-dapp/server-config.js
  web-dapp/server.js
  web-dapp/src/components/App.test.js
  web-dapp/src/components/ConfirmationPage.test.js
  web-dapp/src/components/RegisterAddressPage.test.js
  web-dapp/src/contract-output.json
  web-dapp/test/server/_utils/contract-output.json
  web-dapp/test/server/_utils/server-config-private.js
  web-dapp/test/server/prepare_con_tx.spec.js
  web-dapp/test/server/prepare_reg_tx.spec.js
Labels: in progress

#81 (Improvement) Activate linter and fix detections
  package.json
  web-dapp/.eslintrc.yml
  web-dapp/package-lock.json
  web-dapp/package.json
  web-dapp/routes/_lists.js
  web-dapp/routes/notify_reg_tx.js
  web-dapp/routes/prepare_con_tx.js
  web-dapp/server-lib/buildSignature.js
  web-dapp/server-lib/generate_code.js
  web-dapp/server-lib/get_address_details.js
  web-dapp/server-lib/get_address_index.js
  web-dapp/server-lib/get_tx_receipt.js
  web-dapp/server-lib/logger.js
  web-dapp/server-lib/send_response.js
  web-dapp/server-lib/validate_address_index.js
  web-dapp/server-lib/validate_tx_info.js
  web-dapp/server-lib/validate_tx_receipt.js
  web-dapp/server-lib/validations.js
  web-dapp/src/.eslintrc.yml
  web-dapp/src/registerServiceWorker.js
  web-dapp/src/setupTests.js
Labels: in progress

#89 (Fix/Refactor) Apply Solhint rules for contracts
  README.md
  blockchain/contracts/Migrations.sol
  blockchain/contracts/ProofOfPhysicalAddress.sol
  blockchain/test/proof_of_physical_address.js
  web-dapp/controllers/prepareConTx.js
  web-dapp/controllers/prepareRegTx.js
  web-dapp/routes/prepare_con_tx.js
  web-dapp/routes/prepare_reg_tx.js
  web-dapp/server-config.js
  web-dapp/server-lib/buildSignature.js
  web-dapp/server-lib/get_address_details.js
  web-dapp/server-lib/get_address_index.js
  web-dapp/server-lib/post_api.js
  web-dapp/server-lib/recalc_price.js
  web-dapp/src/components/ConfirmationPage.js
  web-dapp/src/components/ConfirmationPage.test.js
  web-dapp/src/components/RegisterAddressPage.js
  web-dapp/src/components/RegisterAddressPage.test.js
  web-dapp/test/server/_utils/contract-output.json
  web-dapp/test/server/_utils/server-config-private.js
  web-dapp/test/server/get_address_details.spec.js
  web-dapp/test/server/notifyRegTx.spec.js
  web-dapp/test/server/prepareConTx.spec.js
  web-dapp/test/server/prepare_con_tx.spec.js
Labels: in progress

#91 (Refactor) Change snake_case to camelCase
  README.md
  utils/deploy_contract.js
  utils/test.js
  utils/utils-config.js
  web-dapp/app.js
  web-dapp/controllers/notifyRegTx.js
  web-dapp/controllers/prepareRegTx.js
  web-dapp/postcard/front.html
  web-dapp/routes/_lists.js
  web-dapp/routes/index.js
  web-dapp/routes/notify_reg_tx.js
  web-dapp/routes/prepare_con_tx.js
  web-dapp/routes/prepare_reg_tx.js
  web-dapp/server-config.js
  web-dapp/server-lib/generate_code.js
  web-dapp/server-lib/get_address_index.js
  web-dapp/server-lib/get_transaction.js
  web-dapp/server-lib/get_tx_receipt.js
  web-dapp/server-lib/log_request.js
  web-dapp/server-lib/post_api.js
  web-dapp/server-lib/recalc_price.js
  web-dapp/server-lib/req_id.js
  web-dapp/server-lib/send_response.js
  web-dapp/server-lib/session-stores/redis.js
  web-dapp/server-lib/session_store.js
  web-dapp/server-lib/sign.js
  web-dapp/server-lib/validate_address_index.js
  web-dapp/server-lib/validate_tx_details.js
  web-dapp/server-lib/validate_tx_info.js
  web-dapp/server-lib/validate_tx_receipt.js
  web-dapp/server.js
  web-dapp/src/components/App.js
  web-dapp/src/components/App.test.js
  web-dapp/src/components/ConfirmationPage.js
  web-dapp/src/components/ConfirmationPage.test.js
  web-dapp/src/components/RegisterAddressPage.js
  web-dapp/src/components/RegisterAddressPage.test.js
  web-dapp/test/server/_utils/contract-output.json
  web-dapp/test/server/_utils/mocks.js
  web-dapp/test/server/generate_code.spec.js
  web-dapp/test/server/get_address_index.spec.js
  web-dapp/test/server/get_transaction.spec.js
  web-dapp/test/server/notifyRegTx.spec.js
  web-dapp/test/server/validate_tx_details.spec.js
Labels: in progress

#92 (Fix) Update README
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: in progress
